title: Boxersteavee's Projects Wiki
description: A wiki containing all my Projects!
theme: just-the-docs
color_scheme: dark
url: https://projects.boxersteavee.dev

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-redirect-from

aux_links:
  GitHub: https://github.com/Boxersteavee/
  Main Site: https://boxersteavee.dev/